# Build all images and run all containers
# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.7'

services:

  etd-base-template:
    container_name: 'etd-base-template'
    build:
      context: './'
      dockerfile: './DockerfileLocal'
    volumes:
      - './:/home/etdadm'
      - '/tmp:/tmp'
    env_file:
      - '.env'
    environment:
      - CELERY_LOG_LEVEL=DEBUG
      - CONSUME_QUEUE_NAME=etd_base_template
      # Worker API
      - '10610:8081'
    networks:
      - etd-net

# Create a custom docker network if it does not exist already
networks:
 etd-net:
    name: etd-net
